package com.classroom.exception;

import org.springframework.web.servlet.NoHandlerFoundException;
import com.classroom.config.RequestCorrelationFilter;
import com.classroom.dto.ApiEnvelope;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.validation.FieldError;
import org.springframework.web.bind.MethodArgumentNotValidException;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;
import org.springframework.web.servlet.resource.NoResourceFoundException;


/**
 * The single place where controller errors are turned into responses. It replaced the
 * private createErrorResponse/generateSessionId methods that were duplicated across four
 * controllers.
 *
 * It covers only the exceptions raised INSIDE the controller method. Refusals at the
 * security-filter level (no token, invalid token) are handled separately by
 * ApiAuthenticationEntryPoint and ApiAccessDeniedHandler, because they happen before the
 * dispatch to the controller - and therefore before this @RestControllerAdvice - takes place.
 *
 * Every userMessage here stays Italian: it is the one field of the envelope a person reads.
 */
@RestControllerAdvice
public class GlobalExceptionHandler {

    private static final Logger logger = LoggerFactory.getLogger(GlobalExceptionHandler.class);

    /**
     * The id of the request in flight, not a new one.
     *
     * This method used to generate one of its own, so the same request appeared in the logs
     * under two different ids: the controller's, and the one produced here while answering.
     * They were unrelated, and there was no way to tell they belonged to the same call.
     */
    private String currentSessionId() {
        return RequestCorrelationFilter.current();
    }

    @ExceptionHandler(MethodArgumentNotValidException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleValidation(MethodArgumentNotValidException ex) {
        String sessionId = currentSessionId();
        FieldError firstError = ex.getBindingResult().getFieldError();
        String userMessage = firstError != null
                ? firstError.getDefaultMessage()
                : "I dati inviati non sono validi.";
        logger.warn("Validation failed: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error("VALIDATION_ERROR", "Request body failed validation", userMessage, sessionId),
                HttpStatus.BAD_REQUEST
        );
    }

    @ExceptionHandler(AccessDeniedException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleAccessDenied(AccessDeniedException ex) {
        String sessionId = currentSessionId();
        // If the message was built explicitly by an application throw, it is preserved;
        // otherwise (a refusal generated by @PreAuthorize, say) a message equivalent to the
        // one already in use for denied admin access is applied.
        String userMessage = ex.getMessage() != null
                ? ex.getMessage()
                : "Accesso negato: privilegi insufficienti per questa operazione.";
        logger.warn("Access denied: {}", userMessage);
        return new ResponseEntity<>(
                ApiEnvelope.error("ACCESS_DENIED", "Access denied", userMessage, sessionId),
                HttpStatus.FORBIDDEN
        );
    }

    /**
     * Input the domain will not accept, which Bean Validation could not have caught, typically
     * because it depends on the domain. IllegalArgumentException is deliberately NOT mapped
     * here: that one signals a programming error, and turning it into a 400 would pass the
     * server's bugs off as the caller's fault.
     */
    @ExceptionHandler(InvalidRequestException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleInvalidRequest(InvalidRequestException ex) {
        String sessionId = currentSessionId();
        // WARN and not DEBUG: it is a 400, like the validation above, and for the same
        // reason - a body that does not honour the contract says something about the caller.
        // They used to sit at two different levels for no reason.
        logger.warn("Invalid request: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error(ex.getErrorCode(), ex.getMessage(), ex.getUserMessage(), sessionId),
                HttpStatus.BAD_REQUEST
        );
    }

    /**
     * A resource that does not exist. This case used to arrive here as a null, and every
     * controller decided for itself that it meant a 404 and with what message: sixteen
     * scattered "== null" checks, each with its own hand-written sentence.
     */
    @ExceptionHandler(ResourceNotFoundException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleResourceNotFound(ResourceNotFoundException ex) {
        String sessionId = currentSessionId();
        // debug and not warn: a resource looked up and not found is a normal outcome of using
        // the application, not a symptom of anything being wrong.
        logger.debug("Resource not found: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error(ex.getErrorCode(), ex.getMessage(), ex.getUserMessage(), sessionId),
                HttpStatus.NOT_FOUND
        );
    }

    /**
     * A conflict with the current state of the data. This also catches BookingConflictException,
     * which is a subtype: the more specific handler below is still preferred by Spring, and it
     * exists to tell the case apart in the logs.
     */
    @ExceptionHandler(DomainConflictException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleDomainConflict(DomainConflictException ex) {
        String sessionId = currentSessionId();
        logger.warn("Domain conflict: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error(ex.getErrorCode(), ex.getMessage(), ex.getUserMessage(), sessionId),
                HttpStatus.CONFLICT
        );
    }

    @ExceptionHandler(BookingConflictException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleBookingConflict(BookingConflictException ex) {
        String sessionId = currentSessionId();
        logger.warn("Booking conflict: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error(ex.getErrorCode(), ex.getMessage(), ex.getUserMessage(), sessionId),
                HttpStatus.CONFLICT
        );
    }

    @ExceptionHandler(DataIntegrityViolationException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleDataIntegrityViolation(DataIntegrityViolationException ex) {
        String sessionId = currentSessionId();
        logger.warn("Database constraint violated: {}", ex.getMessage());
        return new ResponseEntity<>(
                ApiEnvelope.error("CONFLICT", "Conflict with the current state of the data",
                        "L'operazione non e' andata a buon fine per un conflitto con dati esistenti.", sessionId),
                HttpStatus.CONFLICT
        );
    }

    /**
     * 503 and not 500: the difference is the action it suggests to whoever reads it.
     *
     * Logged at WARN rather than ERROR, with the stack trace: an unreachable downstream
     * service is not a defect of this service, but the cause has to be visible - "not
     * answering" on its own does not separate a refused connection from a timeout, and those
     * are two different diagnoses.
     */
    @ExceptionHandler(ServiceUnavailableException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleServiceUnavailable(ServiceUnavailableException ex) {
        String sessionId = currentSessionId();
        logger.warn("Downstream service unavailable: {}", ex.getMessage(), ex);
        return new ResponseEntity<>(
                ApiEnvelope.error(ex.getErrorCode(), ex.getMessage(), ex.getUserMessage(), sessionId),
                HttpStatus.SERVICE_UNAVAILABLE
        );
    }

    /**
     * A path that does not exist has to stay a 404. Without this handler it fell through to
     * handleGeneric and became a 500 INTERNAL_ERROR, logged as an error into the bargain: a
     * client's wrong path is not a server fault.
     *
     * The case surfaced when springdoc was switched off in production, which leaves
     * /v3/api-docs and /swagger-ui.html as permitAll paths that do not exist. It went
     * unnoticed on protected paths, because security answers 401 before reaching here.
     */
    @ExceptionHandler(NoResourceFoundException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleResourceNotFound(NoResourceFoundException ex) {
        String sessionId = currentSessionId();
        logger.debug("Resource not found: {}", ex.getResourcePath());
        return new ResponseEntity<>(
                ApiEnvelope.error("NOT_FOUND", "Resource not found",
                        "L'indirizzo richiesto non esiste.", sessionId),
                HttpStatus.NOT_FOUND
        );
    }

    /**
     * A path that does not exist, when there is NO static-resource handler.
     *
     * It is the twin of handleResourceNotFound, and it is needed because Spring picks one
     * exception or the other depending on the configuration: with static resources active an
     * unknown path reaches their handler and produces NoResourceFoundException; without them
     * - and booking-service is without, since the SPA was removed - it arrives here as
     * NoHandlerFoundException.
     *
     * It was missing, and the consequence was that that service answered 500 "internal error"
     * to any wrong address instead of 404. A defect found by querying the three services and
     * noticing that one answered differently from the other two.
     */
    @ExceptionHandler(NoHandlerFoundException.class)
    public ResponseEntity<ApiEnvelope<Void>> handleNoHandler(NoHandlerFoundException ex) {
        String sessionId = currentSessionId();
        logger.debug("No handler for {} {}", ex.getHttpMethod(), ex.getRequestURL());
        return new ResponseEntity<>(
                ApiEnvelope.error("NOT_FOUND", "Resource not found",
                        "L'indirizzo richiesto non esiste.", sessionId),
                HttpStatus.NOT_FOUND
        );
    }

    @ExceptionHandler(Exception.class)
    public ResponseEntity<ApiEnvelope<Void>> handleGeneric(Exception ex) {
        String sessionId = currentSessionId();
        logger.error("Unhandled internal error", ex);
        return new ResponseEntity<>(
                ApiEnvelope.error("INTERNAL_ERROR", "Unhandled internal error",
                        "Si e' verificato un errore imprevisto. Se il problema persiste, contatta il supporto tecnico.", sessionId),
                HttpStatus.INTERNAL_SERVER_ERROR
        );
    }
}
