-- ============================================================================
-- A booking stops pointing at the users table.
--
-- The users are about to move to auth-service, with a database of their own: a foreign key
-- to a table that will not be here any more cannot survive. In its place the bookings keep a
-- SNAPSHOT of whoever booked, with the same three fields the API already exposed
-- (id, username, name).
--
-- CAREFUL, this is a real loss of guarantee: while the FK exists the database prevents
-- orphan bookings. After this migration nothing prevents them any more, and deleting a user
-- becomes the application's responsibility. That is the price of the split, not a side
-- effect to be discovered afterwards.
--
-- The snapshot is deliberate: it shows who booked AS THEY WERE THEN. A user who changes
-- their name does not rewrite history, and these fields must not be resynchronised.
-- ============================================================================

ALTER TABLE prenotazioni ADD COLUMN IF NOT EXISTS utente_username varchar(50);
ALTER TABLE prenotazioni ADD COLUMN IF NOT EXISTS utente_nome     varchar(100);

-- Filled in while the two tables are still in the same database: after the split this join
-- could no longer be written.
UPDATE prenotazioni p
   SET utente_username = u.username,
       utente_nome     = u.nome
  FROM utenti u
 WHERE u.id = p.utente_id
   AND (p.utente_username IS NULL OR p.utente_nome IS NULL);

-- The utente_id column stays: what changes is only that it is no longer a foreign key. The
-- constraint's name is generated by PostgreSQL, so it is looked up in the catalogue rather
-- than guessed.
DO $$
DECLARE
    nome_vincolo text;
BEGIN
    SELECT con.conname INTO nome_vincolo
      FROM pg_constraint con
      JOIN pg_class rel ON rel.oid = con.conrelid
     WHERE rel.relname = 'prenotazioni'
       AND con.contype = 'f'
       AND con.confrelid = 'utenti'::regclass;

    IF nome_vincolo IS NOT NULL THEN
        EXECUTE format('ALTER TABLE prenotazioni DROP CONSTRAINT %I', nome_vincolo);
    END IF;
END $$;
